#!/usr/bin/env bash
# =============================================================================
# lib/seed-generator.sh — Cloud-init NoCloud seed-ISO builder
# =============================================================================
# Public:
#   seed_generator_build REPO_URL HOSTNAME OUTPUT_DIR
#       Render a cloud-init `user-data` document parameterised by REPO_URL
#       and HOSTNAME, build a NoCloud `seed.iso` from it via cloud-localds,
#       and print the absolute path of the produced ISO on stdout.
#
#       The runcmd inside the user-data, in order:
#         1. Redirect stdout/stderr of subsequent commands to /dev/ttyS0.
#         2. rm any prior /root/dotfiles clone.
#         3. git clone REPO_URL into /root/dotfiles.
#         4. cd into the clone's .os/ directory.
#         5. sed-patch the system.hostname field of install.jsonc to HOSTNAME.
#         6. ./install.sh --unattended  (capture exit code into $rc).
#         7. printf '===INSTALLER-EXIT-%d===\n' "$rc" > /dev/ttyS0
#         8. sync && poweroff -f
#
#       The exact line `===INSTALLER-EXIT-N===` is the contract consumed by
#       lib/sentinel-watcher.sh on the host. Do not change the format.
#
#       Returns non-zero if `cloud-localds` is missing — the orchestrator,
#       not this module, is responsible for installing it.
#
# Test seam:
#   _seed_generator_render_user_data REPO_URL HOSTNAME
#       Echo the user-data document text without invoking cloud-localds.
#       Tests use this to assert substitution and runcmd shape without
#       requiring cloud-image-utils on the test host.
# =============================================================================

# ── Internal: render user-data text ───────────────────────────────────────────
# Substitution happens via shell expansion inside the heredoc, so the produced
# text contains literal values for REPO_URL and HOSTNAME — no leftover
# placeholders.

_seed_generator_render_user_data() {
  local repo_url="$1" hostname="$2"
  cat <<EOF
#cloud-config
# Generated by .os/lib/seed-generator.sh — do not edit by hand.
# Consumed by archiso's NoCloud datasource on first boot.
runcmd:
  - exec > /dev/ttyS0 2>&1
  - rm -rf /root/dotfiles
  - git clone ${repo_url} /root/dotfiles
  - cd /root/dotfiles/.os
  - sed -i 's|"hostname"[[:space:]]*:[[:space:]]*"[^"]*"|"hostname": "${hostname}"|' install.jsonc
  - ./install.sh --unattended; rc=\$?
  - printf '===INSTALLER-EXIT-%d===\n' "\$rc" > /dev/ttyS0
  - sync
  - poweroff -f
EOF
}

# ── Public API ────────────────────────────────────────────────────────────────

seed_generator_build() {
  local repo_url="$1" hostname="$2" out_dir="$3"

  [[ -n "$repo_url" ]] || {
    echo "seed-generator: REPO_URL is empty" >&2
    return 1
  }
  [[ -n "$hostname" ]] || {
    echo "seed-generator: HOSTNAME is empty" >&2
    return 1
  }
  [[ -d "$out_dir" ]] || {
    echo "seed-generator: output directory does not exist: $out_dir" >&2
    return 1
  }

  command -v cloud-localds >/dev/null 2>&1 || {
    echo "seed-generator: cloud-localds not found — install cloud-image-utils" >&2
    return 1
  }

  local user_data="${out_dir%/}/user-data"
  local seed_iso="${out_dir%/}/seed.iso"

  _seed_generator_render_user_data "$repo_url" "$hostname" > "$user_data"

  cloud-localds "$seed_iso" "$user_data" >/dev/null || {
    echo "seed-generator: cloud-localds failed for $user_data" >&2
    return 1
  }

  [[ -s "$seed_iso" ]] || {
    echo "seed-generator: cloud-localds produced no output at $seed_iso" >&2
    return 1
  }

  printf '%s\n' "$seed_iso"
}
