#!/usr/bin/env bash
# lib/chroot/bootloader-grub.sh — Bootloader Adapter: GRUB
# Runs inside arch-chroot. Reads install-state.json via install-state.sh.
set -Eeuo pipefail
trap 'echo "[chroot:bootloader-grub] failed at line $LINENO" >&2' ERR

# shellcheck source=./install-state.sh
STATE="${STATE:-/root/lib-chroot/install-state.json}"
_LIB_DIR="$(dirname "${BASH_SOURCE[0]}")"
_INSTALL_STATE_SH="$_LIB_DIR/install-state.sh"
[[ -f "$_INSTALL_STATE_SH" ]] || _INSTALL_STATE_SH="$_LIB_DIR/../install-state.sh"
# shellcheck disable=SC1090
source "$_INSTALL_STATE_SH"
install_state_load "$STATE"

POOL_ROOT="$RPOOL/ROOT/arch"

# GRUB can read ZFS pools natively — kernel/initramfs stay on the ZFS dataset.
# grub-install writes the EFI binary; grub-mkconfig generates grub.cfg.
grub-install \
    --target=x86_64-efi \
    --efi-directory=/boot/efi \
    --bootloader-id=GRUB \
    --recheck

cat > /etc/default/grub << EOF
GRUB_DEFAULT=0
GRUB_TIMEOUT=4
GRUB_DISTRIBUTOR="Arch Linux (ZFS)"
GRUB_CMDLINE_LINUX_DEFAULT="quiet"
GRUB_CMDLINE_LINUX="root=ZFS=${POOL_ROOT}"
GRUB_PRELOAD_MODULES="zfs"
GRUB_DISABLE_OS_PROBER=false
EOF

grub-mkconfig -o /boot/grub/grub.cfg
echo "GRUB installed. Boot entries generated by grub-mkconfig."
