#!/usr/bin/env bash
# lib/chroot/bootloader-grub.sh — Bootloader Adapter: GRUB
# Dispatched by configure.sh inside arch-chroot when options.bootloader=grub.
# Thin entry point over the shared installer (lib/grub-common.sh, staged here as
# /root/lib-chroot/grub-common.sh by configure_system).
set -Eeuo pipefail
trap 'echo "[chroot:bootloader-grub] failed at line $LINENO" >&2' ERR

_LIB_DIR="$(dirname "${BASH_SOURCE[0]}")"

# Load install-state (KERNEL) + the kernel token table (kernel_pkg) so the
# Primary Kernel can be pinned as GRUB's default boot entry (ADR 0038).
STATE="${STATE:-/root/lib-chroot/install-state.json}"
_INSTALL_STATE_SH="$_LIB_DIR/install-state.sh"
[[ -f "$_INSTALL_STATE_SH" ]] || _INSTALL_STATE_SH="$_LIB_DIR/../install-state.sh"
# shellcheck disable=SC1090
source "$_INSTALL_STATE_SH"
install_state_load "$STATE"

_KERNEL_SH="$_LIB_DIR/kernel.sh"
[[ -f "$_KERNEL_SH" ]] || _KERNEL_SH="$_LIB_DIR/../packages/kernel.sh"
# shellcheck disable=SC1090
source "$_KERNEL_SH"

# shellcheck source=../grub-common.sh
source "${_LIB_DIR}/grub-common.sh"

# zswap cmdline fragment (empty unless swap + zswap are both enabled).
_ZSWAP_SH="$_LIB_DIR/zswap.sh"
[[ -f "$_ZSWAP_SH" ]] || _ZSWAP_SH="$_LIB_DIR/../boot/zswap.sh"
# shellcheck disable=SC1090
source "$_ZSWAP_SH"

grub_install_and_configure "$(kernel_pkg "$KERNEL")" \
  "$(zswap_cmdline_params "$(cat "$STATE")")"
echo "GRUB installed. Boot entries generated by grub-mkconfig."
