#!/usr/bin/env bash
# =============================================================================
# lib/matrix/records.sh — committed Combination Matrix records (ADR 0046)
# =============================================================================
# The reviewable, CI-enforced trail for the matrix (issue 08):
#
#   Matrix Manifest   the Tier-2 set — the expensive, selective cells worth
#                     pinning/reproducing — one JSON cell per line, sorted.
#   Coverage summary  a diffable snapshot of resolved axes → values →
#                     exclusions + per-tier cell counts. It is the DRIFT GUARD
#                     for the constraint model: a silent shrink (fewer valid
#                     cells) that Tier-1 bats still passes shows here as a
#                     one-line change + a count delta, not a wall of vanished
#                     manifest rows.
#
# Both are menu-derived (via the generator), so they can only change when the
# menu / constraints change — which is exactly when CI should demand a regen.
#
# Pure: text on stdout, no TTY. Requires OS_DIR (menu functions).
#
# Public API:
#   matrix_manifest [seed]           → the Tier-2 manifest (JSON cell / line)
#   matrix_coverage_summary [seed]   → the coverage summary text
#   matrix_records_write [m] [c] [seed]  → write both records (after the gate)
#   matrix_records_paths             → the two default committed record paths
# =============================================================================

# shellcheck source=./generator.sh
declare -F matrix_tier2_cells >/dev/null 2>&1 \
  || source "${BASH_SOURCE[0]%/*}/generator.sh"
# shellcheck source=./registry.sh
declare -F matrix_registry_assert >/dev/null 2>&1 \
  || source "${BASH_SOURCE[0]%/*}/registry.sh"

# the committed record paths (env-overridable; default under tests/vm/).
matrix_manifest_path() {
  printf '%s\n' \
    "${MATRIX_MANIFEST_PATH:-$OS_DIR/tests/vm/matrix-manifest.jsonl}"
}
matrix_coverage_path() {
  printf '%s\n' "${MATRIX_COVERAGE_PATH:-$OS_DIR/tests/vm/matrix-coverage.txt}"
}

# matrix_manifest [seed] — the committed Tier-2 set, one JSON cell per line,
# sorted by id (matrix_tier2_cells already unique_by(.id), so it is stable).
matrix_manifest() {
  matrix_tier2_cells "${1:-0}"
}

# matrix_coverage_summary [seed] — the diffable coverage snapshot. Sections:
# [axes] (each install-affecting axis → its sorted value domain, one line),
# [exclusions] (the menu-derived forbidden combos, one sorted line each), and
# [counts] (per-tier cell totals). Deterministic for a fixed seed.
matrix_coverage_summary() {
  local seed="${1:-${MATRIX_SEED:-0}}" axes cons t2cells t1 t2 t2s t2p
  axes="$(_matrix_tier2_axes)"
  cons="$(_matrix_tier2_constraints)"
  t1="$(matrix_tier1_cells | grep -c .)"
  t2cells="$(matrix_tier2_cells "$seed")"
  t2="$(printf '%s\n' "$t2cells" | grep -c .)"
  t2s="$(printf '%s\n' "$t2cells" \
    | jq -r 'select(.id | startswith("seed-")) | .id' | grep -c . || true)"
  t2p=$((t2 - t2s))

  printf '# Combination Matrix coverage — generated by matrix.sh gen.\n'
  printf '# Menu-derived; do not edit — regenerate on any menu change.\n\n'
  printf '[axes]\n'
  jq -r 'to_entries | sort_by(.key)[]
         | "\(.key): \([.value[] | tostring] | sort | join(" "))"' <<<"$axes"
  printf '\n[exclusions]\n'
  jq -r '[.[] | (to_entries | sort_by(.key)
                 | map("\(.key)=\(.value | tostring)") | join(" "))]
         | sort[]' <<<"$cons"
  printf '\n[counts]\n'
  printf 'tier1: %s\n' "$t1"
  printf 'tier2-pairwise: %s\n' "$t2p"
  printf 'tier2-seeds: %s\n' "$t2s"
  printf 'tier2-total: %s\n' "$t2"
}

# matrix_records_write [manifest] [coverage] [seed] — regenerate and write both
# committed records. Runs the Axis Registry gate first, so an unclassified menu
# field aborts before any file is touched (the matrix can't drift). Paths
# default to the committed locations (env-overridable). Status on stderr.
matrix_records_write() {
  local mpath="${1:-$(matrix_manifest_path)}"
  local cpath="${2:-$(matrix_coverage_path)}"
  local seed="${3:-${MATRIX_SEED:-0}}"
  matrix_registry_assert || return 1
  matrix_manifest "$seed" >"$mpath"
  matrix_coverage_summary "$seed" >"$cpath"
  echo "matrix: wrote $mpath + $cpath" >&2
}
