#!/usr/bin/env bash

function network_info() {
  echo "--------------- Network Information ---------------"
  ip addr show | awk '/inet / {print "IP Address:",$2} /inet /{print "Netmask:",$4} /ether /{print "MAC Address:",$2} '
  echo "---------------------------------------------------"
}