#!/usr/bin/env bash

function whatsmyip () {
  # Dumps a list of all IP addresses for every device
  # /sbin/ifconfig |grep -B1 "inet addr" |awk '{ if ( $1 == "inet" ) { print $2 } else if ( $2 == "Link" ) { printf "%s:" ,$1 } }' |awk -F: '{ print $1 ": " $3 }';

  # Internal IP Lookup
  local internal_ip
  internal_ip=$(ip addr show | awk '/inet / {print $2}' | cut -d '/' -f 1)
  echo "Internal IP: ${internal_ip}"

  # External IP Lookup
  local external_ip
  external_ip=$(curl -s http://ifconfig.me/ip)
  if [ -z "${external_ip}" ]; then
      echo "Failed to retrieve external IP address"
  else
      echo "External IP: ${external_ip}"
  fi
}