#!/usr/bin/env bash
# Saves a DRIFT SNAPSHOT of the running system's explicitly-installed packages
# to .installer/hosts/<profile>/pkglist-repo.txt and pkglist-aur.txt.
#
# Usage: save-pkglist.sh [profile]
#   profile defaults to $SAVE_PKGLIST_PROFILE, else $(hostname)
#
# Takes a PROFILE name, not a hostname: ADR 0020 decoupled the two, so a
# machine whose hostname is `eterniox` installs from the profile `desktop`.
# Deriving the directory from $(hostname) is what made this tool exit "No host
# dir" on every real machine.
#
# The output is a drift-recovery artifact, NOT a profile source. It is a flat
# `pacman -Qqen` dump, so replaying it into a profile would collapse Host Core,
# the host delta and every derived set into one host's list — undoing the
# layering on first use. Diff against it; never author from it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALLER_DIR="$(dirname "$SCRIPT_DIR")"

profile="${1:-${SAVE_PKGLIST_PROFILE:-$(hostname)}}"
host_dir="${INSTALLER_DIR}/hosts/${profile}"
[[ -d "$host_dir" ]] || host_dir="${INSTALLER_DIR}/hosts/vm/${profile}"

if [[ ! -d "$host_dir" ]]; then
  {
    echo "save-pkglist: no profile '${profile}' under ${INSTALLER_DIR}/hosts/"
    echo "This takes a PROFILE name (a hosts/<name>/ directory), not a"
    echo "hostname — ADR 0020 decoupled the two."
    echo "Available profiles:"
    for d in "${INSTALLER_DIR}"/hosts/*/ "${INSTALLER_DIR}"/hosts/vm/*/; do
      [[ -f "${d}profile.jsonc" ]] || continue
      n="$(basename "$d")"
      [[ "$n" == "core" ]] && continue
      echo "  - $n"
    done
  } >&2
  exit 1
fi

# The header every consumer sees first. `pacman -S --needed - < file` would
# choke on it, which is deliberate: install-pkglist.sh strips it, ad-hoc
# replays fail loudly rather than silently flattening the layering.
_stamp() {
  printf '# DRIFT SNAPSHOT — %s — profile: %s — %s\n' \
    "$1" "$profile" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '# Generated by tools/save-pkglist.sh from the RUNNING system.\n'
  printf '# Do NOT replay into a profile: this is a flat dump that would\n'
  printf '# collapse Host Core, the host delta and every derived set into\n'
  printf '# one list. Use it to DIFF against the resolved set instead:\n'
  printf '#   tools/explain-packages.sh %s\n' "$profile"
}

{ _stamp "repo (pacman -Qqen)"; pacman -Qqen; } > "${host_dir}/pkglist-repo.txt"
{ _stamp "aur (pacman -Qqem)";  pacman -Qqem; } > "${host_dir}/pkglist-aur.txt"

echo "Saved drift snapshot to ${host_dir}/"
