#!/usr/bin/env bash
# =============================================================================
# vm/lib/flow-test.sh — disposable test VM flow (--testing)
# =============================================================================
# Sourced by vm/vm.sh alongside core.sh. Boots a throwaway libvirt VM headless,
# runs install.sh --unattended via a cloud-init runcmd seed, captures the serial
# console, waits for the ===INSTALLER-EXIT-N=== sentinel, and propagates the
# installer's exit code (0 ok / 124 timeout / 125 boot-fail). Opt-in boot-verify
# (--verify-boot or VERIFY_BOOT) ejects the cdroms, optionally permutes data
# disks (reorder) and corrupts the live zpool.cache (dirty-cache), boots the
# installed disk, and waits for the first-boot sentinel — driven entirely by the
# profile's verify block (boot/by_id/reorder/dirty_cache/pools/mounts/owned).
#
# Consumes (set by vm.sh): VM_NAME, VM_DISK_SIZES[], VM_RAM_MB, VM_VCPUS,
# INSTALL_CONFIG_CONTENT, RECREATE, VERIFY_BOOT, DIRTY_CACHE,
# VM_REORDER_BOOT_DISKS, VM_VERIFY_BYID, VM_VERIFY_POOLS[], VM_VERIFY_MOUNTS[],
# VM_VERIFY_OWNED[].
# =============================================================================

FLOW_TEST_DIR="$(cd "${BASH_SOURCE[0]%/*}" && pwd)"
# core.sh provides the shared host-side functions + defaults; guard-source so
# vm.sh sourcing core first does not double-source.
# shellcheck source=./core.sh
[[ "$(type -t core_resolve_iso)" == function ]] \
  || source "${FLOW_TEST_DIR}/core.sh"
# shellcheck source=./seed-generator.sh
source "${FLOW_TEST_DIR}/seed-generator.sh"
# shellcheck source=./sentinel-watcher.sh
source "${FLOW_TEST_DIR}/sentinel-watcher.sh"

# Per-flow virt-install graphics (headless).
FLOW_GRAPHICS_ARGS=(--graphics none)

# Flow defaults (env overrides win; timeouts also resolved env>profile>here).
: "${TEST_VM_DIR:=${FLOW_TEST_DIR%/vm/lib}/tests/vm}"
: "${CACHE_DIR:=${TEST_VM_DIR}/.vm-test}"
: "${LOG_FILE:=${TEST_VM_DIR}/${VM_NAME}.log}"
: "${BOOT_LOG_FILE:=${TEST_VM_DIR}/${VM_NAME}-boot.log}"
: "${TIMEOUT_SEC:=1800}"
: "${BOOT_TIMEOUT_SEC:=600}"
# Fixture HTTP server (the secure profile's Test Age Key is fetched by the
# Secrets Module at http://<gateway>:<port>/key.age during install). Ported from
# the persistent flow; only stood up when a profile declares fixtures.
: "${HTTP_PORT:=9876}"
_HTTP_PID=""

# Verify-block knobs (default off so a plain install profile behaves vanilla).
: "${VERIFY_BOOT:=false}"
: "${DIRTY_CACHE:=false}"
: "${VM_REORDER_BOOT_DISKS:=false}"
: "${VM_VERIFY_BYID:=false}"
: "${VM_VERIFY_RESILIENCE:=false}"

# =============================================================================
# SEED — cloud-init runcmd, install.jsonc injected base64 (all profile types)
# =============================================================================
# Always injects the resolved install.jsonc (the profile resolver is the single
# source of truth). The first-boot verify block is chosen from the profile's
# verify data: pools present → the pool verifier (lib/vm-pool-verify.sh); else a
# plain boot sentinel. DIRTY_CACHE corrupts the live zpool.cache before install.
_flow_render_user_data() {
  local repo_url="$1" config_b64
  config_b64="$(printf '%s' "${INSTALL_CONFIG_CONTENT}" | base64 -w 0)"

  local dirty_step=""
  [[ "${DIRTY_CACHE}" == "true" ]] && \
    dirty_step='mkdir -p /etc/zfs && printf %s garbage-not-an-nvlist > /etc/zfs/zpool.cache && '

  local boot_block=""
  if [[ "${VERIFY_BOOT}" == "true" ]]; then
    if [[ "${VM_VERIFY_RESILIENCE}" == "true" ]]; then
      boot_block="$(_seed_generator_esp_resilience_firstboot_block)"
    elif [[ -n "${VM_VERIFY_POOLS[*]:-}" ]]; then
      boot_block="$(_seed_generator_multi_firstboot_block \
        "${VM_VERIFY_POOLS[*]:-}" "${VM_VERIFY_MOUNTS[*]:-}" \
        "${VM_VERIFY_BYID:-false}" "${VM_VERIFY_OWNED[*]:-}")"
    else
      boot_block="$(_seed_generator_firstboot_block)"
    fi
  fi

  cat <<EOF
#cloud-config
# Generated by vm/lib/flow-test.sh — do not edit by hand.
output: {all: '| tee -a /dev/ttyS0'}
runcmd:
  - |
    set +e
    set -x
    {
      pacman -Sy --noconfirm --needed git \\
        && rm -rf /root/dotfiles \\
        && git clone ${repo_url} /root/dotfiles \\
        && printf '%s' '${config_b64}' | base64 -d \
  > /root/dotfiles/.os/install.jsonc \\
        && cd /root/dotfiles/.os \\
        && export INSTALL_ENC_PASSPHRASE='testtest' \\
        && export SECRETS_AGE_PASSPHRASE='test' \\
        && ${dirty_step}./install.sh --unattended install.jsonc
    }
    rc=\$?
${boot_block}
    printf '===INSTALLER-EXIT-%d===\n' "\$rc" > /dev/ttyS0
    sync
    poweroff -f
EOF
}

_flow_build_seed() {
  local user_data="${CACHE_DIR}/${VM_NAME}-user-data"
  local seed_iso="${CACHE_DIR}/${VM_NAME}-seed.iso"
  _flow_render_user_data "${REPO_URL}" > "${user_data}"
  cloud-localds "${seed_iso}" "${user_data}" >/dev/null \
    || error "cloud-localds failed for ${user_data}"
  [[ -s "${seed_iso}" ]] || \
    error "cloud-localds produced empty seed at ${seed_iso}"
  printf '%s\n' "${seed_iso}"
}

# =============================================================================
# CONSOLE CAPTURE — script(1) provides the pseudo-TTY virsh console needs
# =============================================================================
CONSOLE_WRAP_PID=""

_start_console_capture() {
  local log="${1:-$LOG_FILE}"
  : > "$log"
  _console_capture_loop "$log" &
  CONSOLE_WRAP_PID=$!
  info "Console capture running — \`tail -F ${log}\` to watch live."
}

# Re-attach `virsh console` until the domain halts, appending to <log>. A serial
# PTY can drop mid-boot — notably on the slower multi-disk boot, when the kernel
# and then serial-getty re-grab the console — and a single non-looping attach
# would then miss the first-boot marker printed afterwards (the VM boots fine but
# the capture dies and the log stays empty). Re-attaching until poweroff makes
# boot-verify robust for multi-disk installs. Stops as soon as the domain is no
# longer running — nothing more will be written.
_console_capture_loop() {
  local log="$1"
  while :; do
    script -qafc "virsh console --force \"$VM_NAME\"" "$log" >/dev/null 2>&1
    _vm_running || break
    sleep 0.3
  done
}

_stop_console_capture() {
  [[ -n "$CONSOLE_WRAP_PID" ]] || return 0
  kill     "$CONSOLE_WRAP_PID" 2>/dev/null || true  # stop the re-attach loop
  pkill -P "$CONSOLE_WRAP_PID" 2>/dev/null || true  # and its live script/virsh
  wait     "$CONSOLE_WRAP_PID" 2>/dev/null || true
  CONSOLE_WRAP_PID=""
}

# Stage declared fixtures into CACHE_DIR and serve it over HTTP on the libvirt
# gateway, so the in-guest Secrets Module can fetch the Test Age Key
# (http://<gateway>:<port>/key.age) during a secure install. No-op when the
# profile declares no fixtures. Smoke-only (live python http.server).
_start_fixture_http_server() {
  _fixture_http_should_serve || return 0
  _stage_fixture_files
  python3 -m http.server "${HTTP_PORT}" \
    --directory "${CACHE_DIR}" \
    --bind "${LIBVIRT_GATEWAY}" \
    >/dev/null 2>&1 &
  _HTTP_PID=$!
  info "Serving fixtures at http://${LIBVIRT_GATEWAY}:${HTTP_PORT}/ (pid ${_HTTP_PID})."
}

# shellcheck disable=SC2329
_stop_fixture_http_server() {
  [[ -n "${_HTTP_PID}" ]] || return 0
  kill "${_HTTP_PID}" 2>/dev/null || true
  _HTTP_PID=""
}

# shellcheck disable=SC2329
_on_signal() { _stop_console_capture; _stop_fixture_http_server; \
  exit "$((128 + ${1:-2}))"; }

# Poll virsh ttyconsole until the serial PTY is assigned, so console capture
# attaches to a live pty instead of dying on "PTY device is not yet assigned".
_wait_for_serial_pty() {
  local _
  for _ in $(seq 1 50); do
    [[ -n "$(virsh ttyconsole "$VM_NAME" 2>/dev/null)" ]] && return 0
    sleep 0.1
  done
  return 0   # best-effort; console capture surfaces any genuine failure
}

# =============================================================================
# BOOT VERIFY (opt-in)
# =============================================================================
# Permute data-disk backing files on the (shut-off) domain so the installed
# system boots with a different /dev/sdX order than it installed under. The OS
# disk stays put. reorder-disks.py is pure + unit-tested (vm-reorder-disks.bats).
_reorder_boot_disks() {
  command -v python3 >/dev/null 2>&1 \
    || { warn "python3 missing — skipping disk reorder."; return 1; }
  local reordered="${CACHE_DIR}/${VM_NAME}-reordered.xml"
  info "Reordering data disks before boot (multi-disk reorder repro)."
  virsh dumpxml --inactive "$VM_NAME" \
    | python3 "${FLOW_TEST_DIR}/reorder-disks.py" > "$reordered" \
    || { warn "Could not render reordered domain XML."; return 1; }
  virsh define "$reordered" >/dev/null \
    || { warn "Could not define reordered domain."; return 1; }
}

# Boots the installed disk and waits for SEED_GENERATOR_FIRSTBOOT_MARKER on the
# serial console. Returns 0 if the marker appears within BOOT_TIMEOUT_SEC, 125
# otherwise (distinct from installer exit codes and the 124 timeout).
_run_boot_verify() {
  section "Verifying installed system boots (timeout: ${BOOT_TIMEOUT_SEC}s)"
  _vm_eject_cdroms
  _vm_running && virsh destroy "$VM_NAME" >/dev/null 2>&1 || true
  if [[ "${VM_REORDER_BOOT_DISKS}" == "true" ]]; then
    _reorder_boot_disks \
      || warn "Disk reorder failed — boot uses the original disk order."
  fi

  info "Booting installed disk → ${BOOT_LOG_FILE}"
  virsh start "$VM_NAME" >/dev/null
  _wait_for_serial_pty
  _start_console_capture "$BOOT_LOG_FILE"

  local brc=0
  set +e
  sentinel_watcher_wait_marker \
    "$BOOT_LOG_FILE" "$SEED_GENERATOR_FIRSTBOOT_MARKER" "$BOOT_TIMEOUT_SEC"
  brc=$?
  set -e

  _stop_console_capture
  _vm_running && virsh destroy "$VM_NAME" >/dev/null 2>&1 || true

  ((brc == 0)) && return 0
  return 125
}

# =============================================================================
# ENTRY POINT
# =============================================================================
flow_test_deps() { _harness_ensure_deps script:util-linux; }

flow_run() {
  trap '_stop_console_capture; _stop_fixture_http_server' EXIT
  trap '_on_signal 2'  INT
  trap '_on_signal 15' TERM

  flow_test_deps
  _ensure_libvirt_group
  _ensure_libvirtd
  mkdir -p "$ISO_DIR" "$CACHE_DIR"

  # Secure profiles fetch the Test Age Key over HTTP during install; stand the
  # server up before the VM boots (no-op when no fixtures are declared).
  _start_fixture_http_server

  section "Resolving Arch ISO"
  local iso; iso="$(core_resolve_iso "$ISO_DIR")"

  section "Building cloud-init seed"
  local seed; seed="$(_flow_build_seed)"
  info "Seed: ${seed}"

  section "VM lifecycle"
  $RECREATE && _vm_destroy_undefine
  if _vm_exists; then
    local current_iso; current_iso="$(_vm_install_iso_path)"
    if [[ -n "$current_iso" && "$current_iso" != "$iso" ]]; then
      info "Existing VM points at stale ISO (${current_iso}); recreating."
      _vm_destroy_undefine
    fi
  fi
  _vm_exists || _vm_create "$iso" "$seed"
  _vm_boot

  section "Capturing installer log → ${LOG_FILE}"
  _wait_for_serial_pty
  _start_console_capture

  section "Waiting for installer (timeout: ${TIMEOUT_SEC}s)"
  local rc=0
  set +e
  sentinel_watcher_wait "$LOG_FILE" "$TIMEOUT_SEC"
  rc=$?
  set -e
  _stop_console_capture

  if   ((rc == 124)); then warn "Installer timed out after ${TIMEOUT_SEC}s."
  elif ((rc == 0));   then info "Installer completed successfully (exit 0)."
  else                     warn "Installer finished with exit code ${rc}."
  fi
  info "Log: ${LOG_FILE}"

  if ((rc == 0)) && [[ "$VERIFY_BOOT" == "true" ]]; then
    if _run_boot_verify; then
      info "Installed system reached the first-boot sentinel — boot OK."
    else
      warn "Installed system did NOT reach the first-boot sentinel" \
           "(boot failed or timed out after ${BOOT_TIMEOUT_SEC}s)."
      info "Boot log: ${BOOT_LOG_FILE}"
      rc=125
    fi
  fi

  exit "$rc"
}
